package dicts

var en_usa_cities []string{
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", "Seattle", "Denver", "Washington", "Boston", "El Paso", "Nashville", "Detroit", "Oklahoma City", "Portland", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Mesa", "Sacramento", "Atlanta", "Kansas City", "Colorado Springs", "Miami", "Raleigh", "Omaha", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tulsa", "Tampa", "Arlington", "New Orleans", "Wichita", "Cleveland", "Bakersfield", "Aurora", "Anaheim", "Honolulu", "Santa Ana", "Riverside", "Lexington", "Henderson", "Stockton", "Saint Paul", "Cincinnati", "St. Louis", "Pittsburgh", "Greensboro", "Anchorage", "Plano", "Orlando", "Newark", "Durham", "Chula Vista", "Toledo", "Fort Wayne", "St. Petersburg", "Jersey City", "Chandler", "Madison", "Lubbock", "Reno", "Buffalo", "Gilbert", "Glendale", "North Las Vegas", "Winston–Salem", "Chesapeake", "Norfolk", "Fremont", "Garland", "Irving", "Richmond", "Boise", "Spokane", "Tacoma", "San Bernardino", "Modesto", "Fontana", "Des Moines", "Moreno Valley", "Santa Clarita", "Fayetteville",
}

var en_usa_streets []string{
  "Main Street", "High Street", "Broadway", "Elm Street", "Maple Street", "Oak Street", "Pine Street", "Cedar Street", "2nd Street", "3rd Street", "4th Street", "5th Street", "Park Avenue", "Washington Street", "Lake Street", "Hill Street", "Walnut Street", "Sunset Boulevard", "Riverside Drive", "Cherry Street", "Chestnut Street", "Spring Street", "Center Street", "1st Avenue", "2nd Avenue", "3rd Avenue", "4th Avenue", "5th Avenue", "6th Avenue", "7th Avenue", "8th Avenue", "9th Avenue", "10th Avenue", "Market Street", "College Avenue", "State Street", "Highland Avenue", "Lincoln Avenue", "Jefferson Street", "Jackson Street", "Franklin Street", "Madison Street", "Adams Street", "Monroe Street", "Van Buren Street", "Grant Street", "Roosevelt Avenue", "Kennedy Boulevard", "Johnson Street", "Harrison Street", "Baker Street", "Canal Street", "Water Street", "Front Street", "Bridge Street", "School Street", "Church Street", "Railroad Street", "Depot Street", "Mill Street", "Smith Street", "Williams Street", "Jones Street", "Brown Street", "Green Street", "Clark Street", "Taylor Street", "Anderson Street", "Thomas Street", "White Street", "King Street", "Queen Street", "Prince Street", "Duke Street", "Court Street", "Union Street", "Division Street", "Prospect Street", "Garden Street", "River Road", "Valley Road", "Mountain Road", "Lakeside Drive", "Meadow Lane", "Grove Street", "Forest Avenue", "Birch Street", "Aspen Street", "Holly Street", "Sycamore Street", "Poplar Street", "Magnolia Street", "Dogwood Street", "Willow Street", "Spruce Street", "Laurel Street", "Ivy Street", "Heather Lane", "Rose Street",
}

var en_usa_states []string{
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming",
}
